apiVersion: v1
kind: Service
metadata:
    name: authenticationms
    namespace: acubed
spec:
    type: LoadBalancer
    ports:
    - port: 50551 
    selector:
        app: authenticationms
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
    name: authenticationms 
    namespace: acubed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authenticationms 
    spec:
      containers:
        - name: authenticationms 
          imagePullPolicy: Always
          image: acubedcr.azurecr.io/authenticationms:buddy
          ports:
          - containerPort: 50551
      imagePullSecrets: 
          - name: 'acubedcr8786ba3e-auth'
