apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: acubed
spec:
  clusterIP: 10.0.165.177
  externalTrafficPolicy: Cluster
  ports:
  - port: 50551
    protocol: TCP
    targetPort: 50551
