apiVersion: v1
kind: Service
metadata:
    name: authenticationms
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: authenticationms
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: authenticationms 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authenticationms 
    spec:
      containers:
        - name: authenticationms 
          image: acubedcr.azurecr.io/authenticationms:buddy
          ports:
          - containerPort: 8080
