apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: authenticationservice 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authenticationservice 
    spec:
      containers:
        - name: authenticationservice 
          image: acubedcr.azurecr.io/authenticationservice
          ports:
          - containerPort: 50551
