apiVersion : apps/v1
kind: Deployment
metadata:
    name: authentication-service 
    namespace: acubed
    labels:
      app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service 
    spec:
      containers:
        - name: authentication-service 
          imagePullPolicy: Never
          image: authentication-service
          ports:
          - containerPort: 50551
