apiVersion: v1
kind: Service
metadata:
    name: authentication-service
    namespace: acubed
    labels:
      app: authentication-service
spec:
    clusterIP: None
    ports:
    - port: 50551 
      name: authentication-service
    selector:
      app: authentication-service