apiVersion: v1
kind: Service
metadata:
    name: authentication-service
    namespace: acubed
spec:
    type: LoadBalancer
    ports:
    - port: 50551 
    selector:
        app: authentication-service
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
    name: authentication-service 
    namespace: acubed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication-service 
    spec:
      containers:
        - name: authentication-service 
          imagePullPolicy: Always
          image: authentication-service
          ports:
          - containerPort: 50551
